package:
  name: mcce
  version: 1.0.0

source:
  git_url: https://github.com/newbooks/Stable-MCCE.git
  git_tag: mcce-conda


requirements:
  build:
    - {{ compiler('gcc') }}
#    - {{ compiler('g++') }}
    - {{ compiler('gfortran') }}

  run:
    - numpy
    - scipy
    - matplotlib
    - pygraphviz
    - pandas
    - xlrd
    - openpyxl

about:
  home: https://gunnerlab.github.io/Stable-MCCE/
  license: MIT